In [1]:
import numpy as np

# Creating, Slicing, Indexing

## Creating arrays

In [2]:
arr = np.array([40,59,60,70])
arr

array([40, 59, 60, 70])

### 1D array

In [3]:
onearr = np.array([30,40,50,60])
np.ndim(arr)

1

### 2D array

In [4]:
twoarr = np.array([[20,30], [40,50]])
np.ndim(arr)

1

### 3D array

In [5]:
threearr = np.array([[[1,2,3],[4,5,6]]])
np.ndim(arr)

1

## Indexing
### Indexing in 1d array

In [6]:
arr = np.array([40,50,60,70,80])
arr[0]

40

In [7]:
arr[1]

50

In [8]:
arr[4]

80

### Indexing in 2d array

In [9]:
tdarray = np.array([[2,3,4],[5,6,7],[7,8,9]])
tdarray[0]

array([2, 3, 4])

In [10]:
tdarray[1]

array([5, 6, 7])

In [11]:
tdarray[2]

array([7, 8, 9])

In [12]:
tdarray[0,1]

3

In [13]:
tdarray[0,:1]

array([2])

In [14]:
tdarray[1,2]

7

## Slicing
### Slicing in 1d array

In [15]:
arr = np.array([10,20,30,40,50,60,70,80,90])
arr[0:5]

array([10, 20, 30, 40, 50])

In [16]:
arr[:5]

array([10, 20, 30, 40, 50])

In [17]:
arr[3:4]

array([40])

In [18]:
arr[4:]

array([50, 60, 70, 80, 90])

In [19]:
arr[:5]

array([10, 20, 30, 40, 50])

### slicing in 2d array

In [20]:
twarray = np.array([[10,20,30], [40,50,60], [70,80,90]])

In [21]:
# first row and 3rd column
twarray[0,2]

30

In [22]:
# 2nd row and 1st column
twarray[1,0]

40

In [23]:
# Third row and 2nd column
twarray[2,1]

80

In [24]:
twarray[2]

array([70, 80, 90])

# Inspecting an array

In [25]:
arr = np.array([[10,20,30,40], [50,60,70,80], [20,40,60,80]])
arr.shape # Number of rows and columns


(3, 4)

In [26]:
arr.size # Number of total elements

12

In [27]:
np.ndim(arr) # Number of dimensions

2

In [28]:
arr.dtype # Datatype

dtype('int32')

In [29]:
len(arr) # Number of nested values

3

In [30]:
arr.astype(float) # convert datatype

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.],
       [20., 40., 60., 80.]])

In [31]:
arr.astype(int)

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [20, 40, 60, 80]])

# Mathematical Operations and Functions on Arrays

In [32]:
# Addition
arr1 = np.array([[10,20,30],[40,50,60],[20,40,60]])
arr2 = np.array([[30,40,50],[30,60,10],[10,20,30]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[ 40  60  80]
 [ 70 110  70]
 [ 30  60  90]]
[[ 40  60  80]
 [ 70 110  70]
 [ 30  60  90]]


In [33]:
# Subtraction
arr1 = np.array([[10,20,30],[40,50,60],[20,40,60]])
arr2 = np.array([[30,40,50],[30,60,10],[10,20,30]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[-20 -20 -20]
 [ 10 -10  50]
 [ 10  20  30]]
[[-20 -20 -20]
 [ 10 -10  50]
 [ 10  20  30]]


In [34]:
# Multiplication
arr1 = np.array([[10,20,30],[40,50,60],[20,40,60]])
arr2 = np.array([[30,40,50],[30,60,10],[10,20,30]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[ 300  800 1500]
 [1200 3000  600]
 [ 200  800 1800]]
[[ 300  800 1500]
 [1200 3000  600]
 [ 200  800 1800]]


In [35]:
# Division
arr1 = np.array([[10,20,30],[40,50,60],[20,40,60]])
arr2 = np.array([[30,40,50],[30,60,10],[10,20,30]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[0.33333333 0.5        0.6       ]
 [1.33333333 0.83333333 6.        ]
 [2.         2.         2.        ]]
[[0.33333333 0.5        0.6       ]
 [1.33333333 0.83333333 6.        ]
 [2.         2.         2.        ]]


In [36]:
# Power
arr1 = np.array([[10,20,30],[40,50,60],[20,40,60]])
arr2 = np.array([[30,40,50],[30,60,10],[10,20,30]])
print(arr1**arr2)
print(np.power(arr1,arr2))

[[1073741824          0          0]
 [         0          0 -972029952]
 [ 797966336          0          0]]
[[1073741824          0          0]
 [         0          0 -972029952]
 [ 797966336          0          0]]


# Combining and Splitting an array

## Combining arrays

In [37]:
# Combine Lists
a = [20,40,60]
b = [10,20,30]
a + b

[20, 40, 60, 10, 20, 30]

In [38]:
arr1 = np.array([20,40,60])
arr2 = np.array([10,20,30])
np.concatenate([arr1, arr2])

array([20, 40, 60, 10, 20, 30])

In [39]:
np.concatenate([arr1,arr2], axis = 0) # Horizontally

array([20, 40, 60, 10, 20, 30])

In [40]:
arr1 = np.array([[20,40,60]])
arr2 = np.array([[10,20,30]])
print(np.concatenate([[arr1,arr2]], axis = 1)) # Matric

[[[20 40 60]]

 [[10 20 30]]]


In [41]:
np.hstack([arr1,arr2]) # Horizontally

array([[20, 40, 60, 10, 20, 30]])

In [42]:
np.vstack([arr1,arr2])

array([[20, 40, 60],
       [10, 20, 30]])

## Splitting an array

In [43]:
longArray = np.array([10,20,30,40,50,60,70,80,90])
np.split(longArray,3)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]

# Adding and removing elements in arrays

## Adding

In [44]:
arr = np.array([1,2,3,4])
np.append(arr,5) # append value at the end
# array, value

array([1, 2, 3, 4, 5])

In [45]:
np.insert(arr,3,7) # insert value at specific index
# array,index,value

array([1, 2, 3, 7, 4])

## Deleting

In [46]:
np.delete(arr,2)

array([1, 2, 4])

# Search, Sort and Filter an array

## Sort array

In [47]:
arr = np.array([3,5,2,8,6,9,1])
np.sort(arr)

array([1, 2, 3, 5, 6, 8, 9])

## Search

In [48]:
np.where(arr == 6)

(array([4], dtype=int64),)

## Filter

In [49]:
arr = np.array([3,2,6,8,1,5,9,7])
print(np.size(arr))
flags = [True, False, False, True, True, False, False, True]
print(len(flags))
print(arr[flags])

8
8
[3 8 1 7]


In [50]:
arr = np.array([3,2,6,8,1,5,9,7])
fa = arr>=5
arr2 = np.sort(arr[fa])
print(arr2)



[5 6 7 8 9]


# Aggregating functions in arrays

In [51]:
price = np.array([40,30,60,80,90,10,20,50,70])
quantity = np.array([50,33,194,122,47,83,25,84,92])
print(price, quantity)
print()
print(np.cumprod([price, quantity], axis = 0))

[40 30 60 80 90 10 20 50 70] [ 50  33 194 122  47  83  25  84  92]

[[   40    30    60    80    90    10    20    50    70]
 [ 2000   990 11640  9760  4230   830   500  4200  6440]]


In [52]:
arr = np.array([4,65,234,67,12,86,90,56,32,12,26,72])
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))
print(np.prod(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

63.0
4
234
756
794820608
[  4  69 303 370 382 468 558 614 646 658 684 756]
[          4         260       60840     4076280    48915360   -88246336
   647764352  1915065344  1152548864   945684480 -1182007296   794820608]


# Statistical Functions

In [53]:
import statistics as stats

In [54]:
carbo = np.array([200,240,210,280.300,245,180,170,175])
np.mean(carbo)

212.5375

In [55]:
np.median(carbo)

205.0

In [57]:
stats.mode(carbo)

200.0

In [58]:
np.std(carbo)

36.811307281187396

In [59]:
np.var(carbo)

1355.07234375

* -1 represents inversely proportional relationship
* 1 represents proportional relationship
* 0 represents no relationship 

In [62]:
tc = np.array([30,50,40,45,60,36,65,40])
deatsh = np.array([100,120,110,135,110,100,112,110])
np.corrcoef([tc,deatsh])

array([[1.        , 0.33549096],
       [0.33549096, 1.        ]])

In [63]:
price = np.array([100, 150,160,130,190,170,200,250])
sale = np.array([15, 12, 10, 13, 8, 9, 7, 5])
np.corrcoef([price,sale])

array([[ 1.        , -0.97991524],
       [-0.97991524,  1.        ]])