In [57]:
import numpy as np

## What is NumPy?
NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

## How to install NumPy?
If you already have python:
```shell
conda install numpy
```
or 
```shell
pip install numpy
```

## How to import NumPy?
```IPython ::python
import numpy as np
```

## What’s the difference between a Python list and a NumPy array?
NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

## Why use NumPy?
NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

## What is an array?
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

In [58]:
z = np.array([[1,2,3],[3,2,1]])
print(z)

[[1 2 3]
 [3 2 1]]


## How to access Elements in the array?
We can access the elements in the array using square brackets. When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you’ll be accessing element “0”.

In [59]:
z[0,0]

1

## What is ndarray?
A “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on.

## What are the attributes of an array?
An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

In [60]:
print(z)

[[1 2 3]
 [3 2 1]]


## How to create a basic array?
To create a NumPy array, you can use the function `np.array()`.

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

In [61]:
arr = np.array([1,2,4,5])
print(arr)

[1 2 4 5]


## How to create an array filled with zeros?

In [62]:
arr = np.array(np.zeros(6))
arr

array([0., 0., 0., 0., 0., 0.])

## How to create an array filled with ones?

In [63]:
arr = np.array([np.ones(5), np.ones(5), np.ones(5)])
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## How to create an empty array?
The function `empty` creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [64]:
emarray = np.empty(5)
emarray

array([1., 1., 1., 1., 1.])

## How to create an array with a range of elements?

```IPython ::python
np.arange(first_number, last_number, step_size)
```

In [65]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## How to create linearly spaced arrays?
We can use `np.linspace()` to create an array with values that are spaced linearly in a specified interval:

In [66]:
arr = np.linspace(4,20,num = 5)
arr

array([ 4.,  8., 12., 16., 20.])

## How to specify datatype in an array?
While the default data type is floating point (`np.float64`), you can explicitly specify which data type you want using the `dtype` keyword.

In [67]:
a = np.array(np.ones(5), dtype = "int64")
# or
b = np.ones(5, dtype = np.float16)
print(a)
print(a.dtype)
print(b)
print(b.dtype)

[1 1 1 1 1]
int64
[1. 1. 1. 1. 1.]
float16


## How to Add, remove & sort elements in an array?
### Sort

In [68]:
arr = np.array([3,2,5,8,2,9,1])
np.sort(arr)

array([1, 2, 2, 3, 5, 8, 9])

### Add or Concatenate
You can add or concatenate two arrays using 
```IPython ::python
np.concatenate(array1, array2)
```

In [69]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate([a,b], axis = 0)
c

array([1, 2, 3, 4, 5, 6])

In [70]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate([[a,b]], axis = 1)
c

array([[1, 2, 3],
       [4, 5, 6]])

## How to Know the shape and size of an array?
`ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

`ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

`ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is `(2, 3)`.

For example, if you create this array:

In [71]:
arr = np.array([[1,2,3,4],[9,7,6,5]])

In [72]:
arr.ndim

2

In [73]:
arr.size

8

In [74]:
arr.shape

(2, 4)

## How to reshape an array?
Using `arr.reshape()` will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array.

In [75]:
arr = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7]])

In [76]:
arr.shape

(3, 4)

In [77]:
arr = arr.reshape(4, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [3, 5, 7]])

## How to convert a 1D array into a 2D array?
### or
## How to add a new axis to an array?
You can use `np.newaxis` and `np.expand_dims` to increase the dimensions of your existing array.

Using `np.newaxis` will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.
You can also expand an array by inserting a new axis at a specified position with `np.expand_dims`.
For example, if you start with this array:

In [78]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [79]:
arr.ndim

1

In [80]:
arr.shape

(6,)

You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis.
For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

In [81]:
arr = arr[np.newaxis ,:]
arr

array([[1, 2, 3, 4, 5, 6]])

In [82]:
arr.ndim

2

In [83]:
arr.shape

(1, 6)

Or, for a column vector, you can insert an axis along the second dimension:

In [84]:
arr = np.array([1,3,4,6])
arr.shape

(4,)

In [85]:
arr[ :, np.newaxis]
arr.shape

(4,)

You can also expand an array by inserting a new axis at a specified position with `np.expand_dims`.

In [86]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np.expand_dims(arr, axis=0)

array([[[1, 2, 3],
        [4, 5, 6]]])

## How do Indexing and Slicing works in Numpy?
You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [88]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[0]

1

In [89]:
arr[3]

4

In [90]:
arr[7]

8

In [91]:
arr[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [92]:
arr[3:]

array([4, 5, 6, 7, 8, 9])

In [93]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

## How to print values of array with certain conditions.

In [94]:
arr = np.array([[3,6,3,7,8], [8,5,2,8,9]])
arr[arr < 5]

array([3, 3, 2])

In [95]:
arr[arr % 2 == 0]

array([6, 8, 8, 2, 8])

## How to select elements that satisfy two conditions?
You can also make use of the logical operators & and | in order to return boolean values that specify whether or not the values in an array fulfill a certain condition. This can be useful with arrays that contain names or other categorical values.

In [96]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr[(arr > 3) & (arr < 10)]

array([4, 5, 6, 7, 8, 9])

## How to create an array from existing data?

In [97]:
arr = np.array([8,3,1,5,7,4,9,2,6,4])
arr

array([8, 3, 1, 5, 7, 4, 9, 2, 6, 4])

In [98]:
arr2 = arr[3:]
arr2

array([5, 7, 4, 9, 2, 6, 4])

In [99]:
arr3, arr4 = np.split(arr,2)
arr3

array([8, 3, 1, 5, 7])

In [100]:
arr4

array([4, 9, 2, 6, 4])

## How to stack two arrays horizontally?
You can stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, arr3 and arr4:

In [101]:
arr5 = np.hstack((arr3, arr4))
arr5

array([8, 3, 1, 5, 7, 4, 9, 2, 6, 4])

## How to stack two arrays vertically?

In [102]:
arr6 = np.vstack((arr3, arr4))
arr6

array([[8, 3, 1, 5, 7],
       [4, 9, 2, 6, 4]])

## How to create a new array object that looks at the same data as the original array?
You can use the `view` method to create a new array object that looks at the same data as the original array (a shallow copy).

In [103]:
arr7 = arr6.view()
arr7[1,4] = 10

In [104]:
arr6

array([[ 8,  3,  1,  5,  7],
       [ 4,  9,  2,  6, 10]])

## How to create a deep copy?
Using the `copy` method will make a complete copy of the array and its data (a deep copy).

In [105]:
arr8 = arr7.copy()
arr8

array([[ 8,  3,  1,  5,  7],
       [ 4,  9,  2,  6, 10]])

## Basic Operations on NumPy Arrays
Once you’ve created your arrays, you can perform addition, subtraction, multiplication, division, and more.

In [106]:
a = np.array([2,7,4,3])
b = np.array([1,8,3,6])

In [107]:
a + b

array([ 3, 15,  7,  9])

In [108]:
a - b

array([ 1, -1,  1, -3])

In [109]:
a * b

array([ 2, 56, 12, 18])

In [110]:
a / b

array([2.        , 0.875     , 1.33333333, 0.5       ])

In [111]:
b / a

array([0.5       , 1.14285714, 0.75      , 2.        ])

In [112]:
a.sum()+b.sum()

34

## What is meant by <strong>Broadcasting</strong>?
<strong>Broadcasting</strong> is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible.

# [Continue Here](http://localhost/numpy/user/absolute_beginners.html#more-useful-array-operations)